### ISSUE TITLE
Standard colors

### ISSUE THREAD

**Issue by GerFr** [GerFr/starshop#125]
only secondary dark , no light grey

**Comment by FritzRa** [comment]
Btw finde ich alle buttons sollten entweder Outline-secondary sein oder outline-dark je nachdem auf welcher helligkeit der Hintergrund ist

**Comment by FritzRa** [comment]
dark,black,secondary benutzen

**Comment by FritzRa** [comment]
Buttons in article

**Comment by FritzRa** [comment]
#134
